name: cloud-unet
channels:
  - conda-forge
dependencies:
  # start app dependenceis
  - pip=22.1.2
  - python=3.10.5
  - numpy=1.23.3
  - scipy=1.9.1
  - tensorflow=2.10.0
  - matplotlib=3.6.0
  - scikit-learn=1.1.2
  # stop app dependencies

  - pip:
    # start app dependencies
    - rasterio==1.3.2
    - patchify==0.2.3
    # stop app dependencies
